### ISSUE TITLE
V4V User Settings broken on update to PeerTube v6.0.1

### ISSUE THREAD

**Issue by ChanoSan** [dhk2/peertube-plugin-lightning#18]
Plugin Version: 5.2.7
PeerTube Version: 6.0.1
Server is running Ubuntu 20.04.6 LTS (focal)

I updated the plugin to latest (5.2.7) just after updating PeerTube to latest (6.0.1). After updating, authorization of Alby wallet in User V4V settings do not work correctly. Attempting to authorize Alby results in an error as shown below:

![image](https://github.com/dhk2/peertube-plugin-lightning/assets/48997871/4b95d357-629c-4b6d-9bc5-297b1f70d7a2)
"Error: error trying to inform peertube of incoming authorization"

Plugin settings can update without any issue, proper API Client ID and Secret remain set up as before. Only User V4V settings cause an error.

**Comment by ChanoSan** [comment]
Oh dear... this is embarrassing.

Please ignore this issue. Error self-resolved, for apparently no reason. Everything works now :p Sorry

**Comment by dhk2** [comment]
No worries, always appreciate the reports, especially when they clear up like that.
