### ISSUE TITLE
Feature Request: Allow Generation of Lightning Invoice QR

### ISSUE THREAD

**Issue by ChanoSan** [dhk2/peertube-plugin-lightning#19]
Some viewers on a PeerTube instance don't have an account, or don't want to log in with one but may still wish to donate over LN.
Similarly, some users may have their Lightning wallet on mobile but not on PC, or at least not integrated with whatever browser they're using on mobile.

In this scenario, it should still be possible to send Lightning payments by having the plugin generate an Invoice QR, which could be scanned to allow payments.

**Comment by dhk2** [comment]
Feature has been there for quite a while as part of the lnurl support
Something may have broken it, I'll check it out.

**Comment by ChanoSan** [comment]
Based on my tests, it functions as expected when I try it from an account logged in with Alby connected, but when I click the Zap button while logged out I only get a blank window:

![Logged in](https://mitra.anon-kenkai.com/media/1f8fa4f420a7f3adc2ed76576d897410a2014cd8b9e7004c84291f8abce612cd.png)

![Logged Out](https://mitra.anon-kenkai.com/media/cc2d1dd8ac0c011eb5bfd6ac699ca1514d5452a35670bd4f53e0f6bcda3c0d74.png)

Video URL: https://peertube.anon-kenkai.com/w/pkoPZzr8x5n4CiFD9iP4VP

afaik I have LNURL enabled in plugin settings.

**Comment by dhk2** [comment]
version 5.5.2 should resolve this

**Comment by ChanoSan** [comment]
Can confirm, works on my end after update. QR code is now displayed.
